name: Continuos Integration

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      withSubmodules: true
      unitTestPaths: test
      minCoverage: 90

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
